# Site settings
title: A Does Of JavaScript
email: jefftschwartz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to my blog "A Does Of JavaScript"! Join me on this
    amazing journey called JavaScript.
baseurl: "/adoseofjavascript" # the subpath of your site, e.g. /blog/
url: "http://jeffschwartz.github.io/" # the base hostname & protocol for your site
twitter_username: jefftschwartz
github_username:  jeffschwartz

# Build settings
markdown: kramdown
